<div class="PhotoMenu">
	<a href="<?php echo App::getUrl('photos/list.php') ?>"><?php echo __('All photos') ?></a>
	<a href="<?php echo App::getUrl('photos/upload.php') ?>"><?php echo __('Upload') ?></a>
	<a href="<?php echo App::getUrl('photos/calendar-list.php') ?>"><?php echo __('Calendars') ?></a>
	<a href="<?php echo App::getUrl('account/settings.php') ?>"><?php echo __('My account') ?></a>
</div>