<div class="PhotoMenu">
	<a href="<?php echo App::getUrl('photos/list.php') ?>"><?php echo __('All photos') ?></a>
	<!--<a href="<?php echo App::getUrl('photos/albums.php') ?>"><?php echo __('Albums') ?></a>-->
	<a href="<?php echo App::getUrl('photos/upload.php') ?>"><?php echo __('Upload') ?></a>
	<a href="<?php echo App::getUrl('photos/calendar/edit.php') ?>"><?php echo __('Calendars') ?></a>
</div>